# Generated by Django 5.2 on 2025-04-25 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    depenarrivalcies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhà xe')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('logo', models.URLField(blank=True, verbose_name='Logo URL')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('rating', models.FloatField(blank=True, default=0, verbose_name='Đánh giá')),
            ],
            options={
                'verbose_name': 'Nhà xe',
                'verbose_name_plural': 'Nhà xe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên bến xe')),
                ('city', models.CharField(max_length=50, verbose_name='Thành phố')),
                ('address', models.CharField(max_length=200, verbose_name='Địa chỉ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
            ],
            options={
                'verbose_name': 'Bến xe',
                'verbose_name_plural': 'Bến xe',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(verbose_name='Khoảng cách (km)')),
                ('duration', models.PositiveIntegerField(verbose_name='Thời gian di chuyển (phút)')),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_routes', to='bus_booking.busstation', verbose_name='Bến đến')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_routes', to='bus_booking.busstation', verbose_name='Bến đi')),
            ],
            options={
                'verbose_name': 'Tuyến đường',
                'verbose_name_plural': 'Tuyến đường',
                'unique_together': {('departure_station', 'arrival_station')},
            },
        ),
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Giờ khởi hành')),
                ('arrival_time', models.DateTimeField(verbose_name='Giờ đến')),
                ('price', models.PositiveIntegerField(verbose_name='Giá vé (VNĐ)')),
                ('bus_type', models.CharField(choices=[('limousine', 'Limousine'), ('sleeper', 'Giường nằm'), ('seater', 'Ghế ngồi'), ('express', 'Xe khách')], max_length=20, verbose_name='Loại xe')),
                ('total_seats', models.PositiveSmallIntegerField(verbose_name='Tổng số ghế')),
                ('amenities', models.TextField(blank=True, verbose_name='Tiện ích')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='bus_booking.buscompany', verbose_name='Nhà xe')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='bus_booking.busroute', verbose_name='Tuyến đường')),
            ],
            options={
                'verbose_name': 'Chuyến xe',
                'verbose_name_plural': 'Chuyến xe',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveSmallIntegerField(verbose_name='Số ghế')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Đã đặt')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bus_booking.bustrip', verbose_name='Chuyến xe')),
            ],
            options={
                'verbose_name': 'Ghế',
                'verbose_name_plural': 'Ghế',
                'unique_together': {('trip', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian đặt')),
                ('passenger_name', models.CharField(max_length=100, verbose_name='Tên hành khách')),
                ('passenger_phone', models.CharField(max_length=20, verbose_name='SĐT hành khách')),
                ('passenger_email', models.EmailField(blank=True, max_length=254, verbose_name='Email hành khách')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy'), ('completed', 'Đã hoàn thành')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bus_booking.bustrip', verbose_name='Chuyến xe')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bus_booking.seat', verbose_name='Ghế')),
            ],
            options={
                'verbose_name': 'Đặt vé',
                'verbose_name_plural': 'Đặt vé',
                'ordering': ['-booking_time'],
            },
        ),
    ]
